### ISSUE TITLE
Various issues (encoding, fetching, updating, and dates)

### ISSUE THREAD

**Issue by cpitclaudel** [greghendershott/feeds2gmail#6]
I've just started looking at feeds2gmail. I had to adjust it a bit to work with outlook.com, but not much. 

I've been running into some issues, however:
- It seems that the emails are created with the date at which the corresponding posts were downloaded. Is that correct? It's usually convenient to be able to know when a post was written.
- When updating from http://oremacs.com/atom.xml I get the following message:
  
  ```
  New: "Easy helm improvement"
  New: "Sometimes things break"
  #(struct:exn:fail:network:errno tcp-read: error reading
    system error: Connection reset by peer; errno=104 #<continuation-mark-set> (104 . posix))
  ```
- When downloading http://blogs.msdn.com/b/oldnewthing/rss.aspx the curly apostrophes are rendered as `â€™`
- When importing a list of feeds, I get
  
  ```
  tcp-read: error reading
    system error: Connection reset by peer; errno=104
  ```
  
  and 
  
  ```
  http://www.dragonwasrobot.com/atom.xml
  match: no matching clause for '(br ())
  http://osa1.net/rss.xml ... 200 OK
  imap-send: unexpected end-of-file from server
  ```

Do you have ideas about any of these issues?
Thanks!

**Comment by greghendershott** [comment]
Thanks for the feedback. I think the short answer is that this project is currently unmaintained. I actively used it successfully for awhile, then stopped using it myself.

I think the weakest aspect of it is the Atom and RSS parsing. Real-world feeds  are "interesting" in how they interpret the spec. (Although many people appreciated the archival aspect of Google Reader, I think the feed-parsing -- and the ongoing maintenance I'm guessing it required -- were probably under-appreciated.)

Anyway, I don't really have time to maintain this actively, these days. If someone else wanted to take it over, I'd be happy to help make that happen.

**Comment by cpitclaudel** [comment]
Thanks Greg. I don't think I have the racket experience to maintain this project (or the time to acquire that experience), unfortunately. Still, I'd be curious to know what other solution you ended up transitioning too; I was quite excited about the feeds -> email idea.

**Comment by greghendershott** [comment]
Sadly I've fallen out of following feeds. Although it's not really equivalent, that's mostly been replaced for me by Twitter (interesting links by people I follow).

**Comment by cpitclaudel** [comment]
Got it, thanks. And yet you maintain a very good blog (though you don't post as often anymore)! I'll close this issue; thanks for the quick reply.
